spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth
    username: postgres
    password: 1403
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23litNMkimHboulsu1
            client-secret: 35c58280c4cf5415aabbbefc2cf334d3742f1afc
            scope: user:email, read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"


logging:
  level:
    org.springframework.security: info
    com.example.demo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/app.log
    path: logs/